version: "3"

services:
  postgres:
    image: postgres:14-alpine
    container_name: java-postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ulab_db