swagger-api:
  version: "1.0"

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:userbook
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

server:
  port: 8091
  servlet:
    context-path: /app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info