swagger-api:
  version: "1.0"

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  datasource:
    url: jdbc:postgresql://localhost:5433/ulab_db
    username: test
    password: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8091
  servlet:
    context-path: /app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info