DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS PERSON;

CREATE TABLE IF NOT EXISTS PERSON
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR (255),
    TITLE VARCHAR (255),
    AGE INTEGER
);

CREATE TABLE IF NOT EXISTS BOOK
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR (255),
    AUTHOR VARCHAR (255),
    PAGE_COUNT INTEGER,
    PERSON_ID BIGINT,
    foreign key (person_id) references Person(id)
);
